# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "miniMe"
COPYRIGHT = "(C) 2010 Michael Risse"

DEPLOY_DIR = "../apache-tomcat-6.0.29/webapps"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2/"
repositories.remote << "http://download.java.net/maven/2/"
repositories.remote << "http://www.ibiblio.org/maven2/"

Project.local_task :deploy
Project.local_task :templates

desc "The Minime project"
define "miniMe" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with "org.apache.openejb:javaee-api:jar:5.0-3", "org:jaudiotagger:jar:2.0.3", "org.xerial:sqlite-jdbc:jar:3.7.2", "log4j:log4j:jar:1.2.9"
  package(:war)

  check package(:war), 'should contain a web.xml' do
    it.should contain('WEB-INF/web.xml')
  end

  check package(:war), 'should contain a web.xml' do
    it.should contain('js/soyutils.js')
  end  

  check package(:war), 'should contain a web.xml' do
    it.should contain('js/templates.js')
  end

  task :deploy => :package do
    FileUtils.cp("target/miniMe-1.0.0.war", "../apache-tomcat-6.0.29/webapps/miniMe.war")
  end

  task :templates do
    #TODO make building the site dependent on this
    #TODO only recompile the templates that need it
    system "java -jar dep/SoyToJsSrcCompiler.jar --outputPathFormat src/main/webapp/js/templates.js jsTemplates/*soy"
  end
end
